-- AlterEnum
ALTER TYPE "ProductType" ADD VALUE 'SERVICE';

-- AlterTable
ALTER TABLE "Product" ADD COLUMN "sacCode" TEXT;

-- AlterTable
ALTER TABLE "ReturnOrder"
  ADD COLUMN "taxableValue" DOUBLE PRECISION,
  ADD COLUMN "gstRate" DOUBLE PRECISION,
  ADD COLUMN "cgst" DOUBLE PRECISION,
  ADD COLUMN "sgst" DOUBLE PRECISION,
  ADD COLUMN "igst" DOUBLE PRECISION,
  ADD COLUMN "taxAmount" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PurchaseReturn"
  ADD COLUMN "taxableValue" DOUBLE PRECISION,
  ADD COLUMN "gstRate" DOUBLE PRECISION,
  ADD COLUMN "cgst" DOUBLE PRECISION,
  ADD COLUMN "sgst" DOUBLE PRECISION,
  ADD COLUMN "igst" DOUBLE PRECISION,
  ADD COLUMN "taxAmount" DOUBLE PRECISION;
